version: '3.11'

services:
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn Weather.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/usr/src/Weather
      - static_volume:/usr/src/Weather/static/
    expose:
      - 8000
    env_file:
      - .env.production
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - .env.production
  redis:
    image: redis
  celery:
    build: .
    command: celery -A Weather worker -l info
    volumes:
      - .:/usr/src/Weather
    env_file:
      - .env.production
    depends_on:
      - db
      - web
      - redis
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/Weather/static/
    ports:
      - "8000:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: